### PR TITLE
PID controller

### PR DESCRIPTION
**Pull request by seiya303**
I implemented a function for PID controlling. Please check it.

### CODE REVIEW

**Comment by lejk8104** [comment]
it is PID control everything?

**Comment by seiya303** [comment]
> it is PID control everything?

Yes, almost everything. But can add time.sleep() to add intervals to the iteration and remove bias or not, I'll add these parts in comments now.

**Comment by Seiya-Umemoto** [comment]
> it is PID control everything?

**Comment by seiya303** [comment]
I revised the commit. Please check it, and if it's okay, please approve and merge it.

**Comment by lejk8104** [comment]
okay

**Comment by lejk8104** [comment]
okay

**Review by lejk8104 — APPROVED** [review]

**Pull request merged**
